_convert_: all
_target_: nuplan_king.planning.simulation.adversary_optimizer.king_optimizer.OptimizationKING
costs_to_use:
- collision
- adv_repulsion
- drivable_efficient
experiment_name: 'Actions_optimized_controller_king_collision_adv_repultion_drivable_stop_10'
collision_strat: stopping_collider
# add comments
loss_weights:
- 1.0
- 40.0
- 1.0
adversary_lrs:
- 0.005
- 0.001
max_opt_iterations: 300
motion_model:
  _convert_: all
  _target_: nuplan_king.planning.simulation.motion_model.bicycle_model.BicycleModel
  delta_t: 0.1
opt_iterations: 200
dense_opt_rounds: 100
requires_grad_params:
- throttle
- steer
actions_to_use: controller
opt_jump: 10


tracker:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 0.01
  - 10.0
  - 0.0
  q_longitudinal:
  - 0.1
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.01
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10



tracker1:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10



tracker2:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10


tracker3:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10




tracker4:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10





tracker5:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10



tracker6:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10


tracker7:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10




tracker8:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10