_convert_: all
_target_: nuplan_king.planning.simulation.adversary_optimizer.king_optimizer.OptimizationKING
costs_to_use:
- nothing
experiment_name: 'default_experiment'
collision_strat: stopping_collider
loss_weights:
- 1.0
- 40.0
lrs:
- 0.005
- 0.001
max_opt_iterations: 300
motion_model:
  _convert_: all
  _target_: nuplan_king.planning.simulation.motion_model.bicycle_model.BicycleModel
  delta_t: 0.1
opt_iterations: 1
dense_opt_rounds: 100
requires_grad_params:
- throttle
- steer



tracker1:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 2



tracker2:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 4


tracker3:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 2




tracker4:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 2





tracker5:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 2



tracker6:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 4


tracker7:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 2




tracker8:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 10.0
  - 100.0
  - 0.0
  q_longitudinal:
  - 100.0
  r_lateral:
  - 20.0
  r_longitudinal:
  - 0.1
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 2