_convert_: all
_target_: nuplan_king.planning.simulation.adversary_optimizer.king_optimizer.OptimizationKING
costs_to_use:
- nothing
experiment_name: 'Reconstructing_parallel_step_optimized'
collision_strat: stopping_collider
# add comments
loss_weights:
- 1.0
- 40.0
adversary_lrs:
- 0.005
- 0.001
max_opt_iterations: 300
motion_model:
  _convert_: all
  _target_: nuplan_king.planning.simulation.motion_model.bicycle_model.BicycleModel
  delta_t: 0.1
opt_iterations: 1
dense_opt_rounds: 100
requires_grad_params:
- throttle
- steer
actions_to_use: parallel_step_optimized


tracker:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 0.01
  - 10.0
  - 0.0
  q_longitudinal:
  - 0.1
  r_lateral:
  - 2.0
  r_longitudinal:
  - 0.01
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10
