_convert_: all
_target_: nuplan_world_coords.planning.simulation.adversary_optimizer.king_optimizer.OptimizationKING
collision_strat: stopping_collider
costs_to_use:
- drivable_us
- moving_dummy
experiment_name: 10_stopping_collider_moving_dummy
loss_weights:
- 1.0
- 40.0
lrs:
- 0.005
- 0.001
max_opt_iterations: 300
motion_model:
  _convert_: all
  _target_: nuplan_world_coords.planning.simulation.motion_model.bicycle_model.BicycleModel
  delta_t: 0.1
opt_iterations: 100
opt_jump: 10
dense_opt_rounds: 10
project_name: collision_strat_loss
requires_grad_params:
- throttle
- steer
tracker:
  curvature_rate_penalty: 1e-2
  jerk_penalty: 1e-4
  q_lateral:
  - 1.0
  - 10.0
  - 0.0
  q_longitudinal:
  - 10.0
  r_lateral:
  - 2.0
  r_longitudinal:
  - 1.0
  stopping_proportional_gain: 0.5
  stopping_velocity: 0.2
  tracking_horizon: 10
